### ISSUE TITLE
Грубые ошибки в разметке (критерий Б2)

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Cat-energy#1]
1. Логотип является ссылкой
https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/index.html#L11

2. Здесь тоже ссылка: https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/index.html#L18
3. Сообщение о затратах не может быть заголовком... Это параграф... https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/index.html#L87
К тому же рекомендую 15000 обернуть в span, это даст возможность при необходимости скриптом легко подставлять нужную сумму
4. В футере социальные сети, логотипы сайта и академии - ссылки
5. Снова ссылка https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/catalog.html#L37

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
Не всё:
https://github.com/ShindekiSan/Cat-energy/blob/475f1c80ea2c5295834bd5550c4162e37dc2472f/catalog.html#L51

**Comment by ShindekiSan** [comment]
Исправил
