### ISSUE TITLE
Заголовок H1

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Cat-energy#2]
Ну, во-первых, на главной странице этот заголовок не второго, а первого уровня
https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/index.html#L15

А во-вторых - рекомендуется всегда располагать на странице заголовок первого уровня, даже если он не прорисован в макете. Одна страница - один заголовок H1. Заголовок должен касаться всего сайта. То есть, например Каталог продукции - это заголовок второго уровня (у тебя всё верно)
https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/catalog.html#L16
Однако заголовка первого уровня на этой странице нет, а должен быть...

**Comment by ShindekiSan** [comment]
Добавил
