### ISSUE TITLE
Реализация ТЗ

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Cat-energy#5]
Техническое задание - основной документ и он обязателен к выполнению. В связи с этим любой фрагмент, не сделанный по ТЗ, автоматически приводит к нарушению критерия Б1, а нарушение любого базового критерия - к не сдаче проекта...

1. Не размечены элементы верхнего меню
2. https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/catalog.html#L18-L21 Нарушение пункта 6.1 ТЗ

**Comment by ShindekiSan** [comment]
Переделал
