### ISSUE TITLE
Декоративные изображения

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Cat-energy#6]
Все декоративные и фоновые изображения и элементы добавляются в проект на этапе стилизации, в разметке они не нужны.
Например, в блоке ниже оба изображения не относятся к контентным. Белая коробочка с бантиком - декор, а кот в рюкзачке - фон.
https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/catalog.html#L218-L224

Пройдись по всей разметке и почисти этот момент
Почитать более подробно можно здесь: https://htmlacademy.ru/blog/boost/frontend/content-or-decor-img

**Comment by ShindekiSan** [comment]
Пересмотрел и поправил
