### ISSUE TITLE
Поля формы

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Cat-energy#7]
Форму размечать тоже надо правильно
1. Правильное значение атрибута type: здесь почта https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/form.html#L53 а здесь телефон https://github.com/ShindekiSan/Cat-energy/blob/ded7926ad05454fae2f13f8968043ba6cf4a4865/form.html#L57
2. Для обязательных полей есть специальный атрибут
3.  Последовательность атрибутов рекомендую писать в таком порядке (при их наличии): class, type, name, id, value, placeholder, вспомогательные атрибуты (required, checked, disabled и т.п.). Это позволит придерживаться общепринятого стиля и легче читать код
4. Атрибут value нужен не для всех типов полей

**Comment by ShindekiSan** [comment]
Переделал

**Comment by Morfey216** [comment]
Не все поля обязательны, будь более внимателен
https://github.com/ShindekiSan/Cat-energy/blob/475f1c80ea2c5295834bd5550c4162e37dc2472f/form.html#L46

**Comment by ShindekiSan** [comment]
Исправил, впредь буду внимательнее
